### ISSUE TITLE
Can't use session_cookies, or need example to do that

### ISSUE THREAD

**Issue by AyraHikari** [tulir/fbchat-asyncio#11]
## Using origin fbchat 
Before i am using asyncio version, this code works for me:
```
with open('session', 'r') as f:
	session_cookies = eval(f.read())
client = AyraMessenger('my_fb_id', 'my_password', session_cookies=session_cookies, logging_level=logging.INFO)
```

To generate session file:
```
client = Client(FB_USERNAME, FB_PASSWORD)
with open('session', 'w') as f:
	f.write(str(client.getSession()))
```

Session file should be a dict, so i am save it as str then get it again as dict with eval

## After move to fbchat-asyncio
Now it look like everything was changed, here is my code from Echo bot example:
```
async def start():
    client = EchoBot(loop=loop)
    print("Logging in...")
    with open('session', 'r') as f:
        session_cookies = eval(f.read())
    await client.start("my_fb_id", "password", session_cookies=session_cookies)
    client.listen()
```

I am not using password because fb will block me from to do this, and need to change password again and again.
So i am using session, but when using session_cookies args it doesn't work or not using that session.

Please add session_cookies support or if it already support, please add guide how to use session_cookies instead of password.

Thanks

**Comment by tulir** [comment]
It does already work, but I'm guessing storing it as a string won't work. Looks like [I'm storing it with pickle](https://github.com/tulir/mautrix-facebook/blob/master/mautrix_facebook/db/user.py#L29), so I'd recommend you try that.

For more specifics of how I'm using it, see these links
* Manual login: https://github.com/tulir/mautrix-facebook/blob/master/mautrix_facebook/commands/auth.py#L123-L127
* Save session: https://github.com/tulir/mautrix-facebook/blob/master/mautrix_facebook/user.py#L93
* Restore session: https://github.com/tulir/mautrix-facebook/blob/master/mautrix_facebook/user.py#L145-L146

Note that `.start()` just calls `set_session`, so both should work. I'm only using `set_session` instead of `start` for more control over the process.

**Comment by AyraHikari** [comment]
Alright got it, thanks for reply

**Comment by AyraHikari** [comment]
Btw how can you solve account locked after login with fbchat?
Everytime i login with fb chat even with simple code my account got locked and need verifying account.
I'm using this code:
```
client = Client()
await client.start(FB_USERNAME, FB_PASSWORD)
```

Then it raise error:
`fbchat._exception.FBchatException: Login failed. Check email/password.`

After that my account got locked and need to verify.

**Comment by tulir** [comment]
Logging in in your browser and copying cookies, matching the user agent in your browser and having 2fa enabled generally help

**Comment by AyraHikari** [comment]
Okay, now it works maybe, but it says Unclosed client session

```
2019-11-27 18:10:05,984 - root - INFO - Set-Cookie: c_user=1000050260xxxxx
Set-Cookie: xs=blablabla
2019-11-27 18:10:10,162 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x042036F0>
2019-11-27 18:10:10,164 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x041EE998>, 180654.859)]']
connector: <aiohttp.connector.TCPConnector object at 0x04203790>
```
